//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/t4models).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------
using System;
using System.Linq;

using LinqToDB;
using LinqToDB.Mapping;

namespace DataModels
{
	/// <summary>
	/// Database       : MyDatabase
	/// Data Source    : C:\Data\MyDatabase.mdb
	/// Server Version : 04.00.0000
	/// </summary>
	public partial class MyDatabaseDB : LinqToDB.Data.DataConnection
	{
		public ITable<person> people { get { return this.GetTable<person>(); } }

		public MyDatabaseDB()
		{
			InitDataContext();
		}

		public MyDatabaseDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
		}

		partial void InitDataContext();
	}

	[Table("person")]
	public partial class person
	{
		[PrimaryKey, Identity] public int    ID   { get; set; } // Long
		[Column,     Nullable] public string Name { get; set; } // text(255)
	}

	public static partial class TableExtensions
	{
		public static person Find(this ITable<person> table, int ID)
		{
			return table.FirstOrDefault(t =>
				t.ID == ID);
		}
	}
}
